language: csharp

mono:
 - latest

os:
 - osx
 - linux

env:
 - TRAVIS_OS_UNAME=$(uname -s)

solution: libsodium-net.sln

install:
 - if [[ $TRAVIS_OS_UNAME = 'Linux' ]]; then bash travis-linux-deps.sh; fi
 - if [[ $TRAVIS_OS_UNAME = 'Darwin' ]]; then bash travis-osx-deps.sh; fi

before_script:
 - bash travis-build-libsodium.sh

script:
 - bash nunit-console.sh ./Tests/bin/Debug/Tests.dll
